[pytest]

pythonpath = .

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --tb=short

markers =
    ui: UI tests
    api_dummy_json: API tests for DummyJSON
    api_restful_booker: API tests for Restful booker

    auth: authentication tests
    cart: tests for cart functionality
    catalog: tests for catalog functionality
    checkout: tests for checkout functionality
    sorting: tests for sorting functionality

    smoke: smoke tests
    regression: regression tests