[pytest]

pythonpath = .

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --tb=short

markers =
    ui: UI tests
    api: API tests

    auth: authentication tests
    cart: tests for cart functionality
    catalog: tests for catalog functionality
    sorting: tests for sorting functionality

    smoke: smoke tests
    regression: regression tests