[pytest]

pythonpath = .

testpaths =
    api/tests
    ui/selenium/tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --tb=short --strict-markers

markers =
    ui: UI tests
    selenium: Selenium UI tests
    playwright: Playwright UI tests
    api: all API tests
    api_dummy_json: API tests for DummyJSON
    api_restful_booker: API tests for Restful booker

    auth: authentication tests
    cart: tests for cart functionality
    catalog: tests for catalog functionality
    checkout: tests for checkout functionality
    sorting: tests for sorting functionality
